window.cardDeck = `[
    {
       "name":"6D",
       "img_back":"/img/cardBack.jpg",
       "img_front":"/img/6Diamonds.png"
    },
    {
       "name":"7D",
       "img_back":"/img/cardBack.jpg",
       "img_front":"/img/7Diamonds.png"
    },
    {
       "name":"8D",
       "img_back":"/img/cardBack.jpg",
       "img_front":"/img/8Diamonds.png"
    },
    {
       "name":"9D",
       "img_back":"/img/cardBack.jpg",
       "img_front":"/img/9Diamonds.png"
    },
    {
       "name":"10D",
       "img_back":"/img/cardBack.jpg",
       "img_front":"/img/10Diamonds.png"
    },
    {
       "name":"JackD",
       "img_back":"/img/cardBack.jpg",
       "img_front":"/img/JackDiamonds.png"
    },
    {
       "name":"QueenD",
       "img_back":"/img/cardBack.jpg",
       "img_front":"/img/QueenDiamonds.png"
    },
    {
       "name":"KingD",
       "img_back":"/img/cardBack.jpg",
       "img_front":"/img/KingDiamonds.png"
    },
    {
       "name":"AceD",
       "img_back":"/img/cardBack.jpg",
       "img_front":"/img/AceDiamonds.png"
    },
    {
       "name":"6C",
       "img_back":"/img/cardBack.jpg",
       "img_front":"/img/6Clubs.png"
    },
    {
       "name":"7C",
       "img_back":"/img/cardBack.jpg",
       "img_front":"/img/7Clubs.png"
    },
    {
       "name":"8C",
       "img_back":"/img/cardBack.jpg",
       "img_front":"/img/8Clubs.png"
    },
    {
       "name":"9C",
       "img_back":"/img/cardBack.jpg",
       "img_front":"/img/9Clubs.png"
    },
    {
       "name":"10C",
       "img_back":"/img/cardBack.jpg",
       "img_front":"/img/10Clubs.png"
    },
    {
       "name":"JackC",
       "img_back":"/img/cardBack.jpg",
       "img_front":"/img/JackClubs.png"
    },
    {
       "name":"QueenC",
       "img_back":"/img/cardBack.jpg",
       "img_front":"/img/QueenClubs.png"
    },
    {
       "name":"KingC",
       "img_back":"/img/cardBack.jpg",
       "img_front":"/img/KingClubs.png"
    },
    {
       "name":"AceC",
       "img_back":"/img/cardBack.jpg",
       "img_front":"/img/AceClubs.png"
    },
    {
       "name":"6S",
       "img_back":"/img/cardBack.jpg",
       "img_front":"/img/6Spades.png"
    },
    {
       "name":"7S",
       "img_back":"/img/cardBack.jpg",
       "img_front":"/img/7Spades.png"
    },
    {
       "name":"8S",
       "img_back":"/img/cardBack.jpg",
       "img_front":"/img/8Spades.png"
    },
    {
       "name":"9S",
       "img_back":"/img/cardBack.jpg",
       "img_front":"/img/9Spades.png"
    },
    {
       "name":"10S",
       "img_back":"/img/cardBack.jpg",
       "img_front":"/img/10Spades.png"
    },
    {
       "name":"JackS",
       "img_back":"/img/cardBack.jpg",
       "img_front":"/img/JackSpades.png"
    },
    {
       "name":"QueenS",
       "img_back":"/img/cardBack.jpg",
       "img_front":"/img/QueenSpades.png"
    },
    {
       "name":"KingS",
       "img_back":"/img/cardBack.jpg",
       "img_front":"/img/KingSpades.png"
    },
    {
       "name":"AceS",
       "img_back":"/img/cardBack.jpg",
       "img_front":"/img/AceSpades.png"
    },
    {
       "name":"6H",
       "img_back":"/img/cardBack.jpg",
       "img_front":"/img/6Hearts.png"
    },
    {
       "name":"7H",
       "img_back":"/img/cardBack.jpg",
       "img_front":"/img/7Hearts.png"
    },
    {
       "name":"8H",
       "img_back":"/img/cardBack.jpg",
       "img_front":"/img/8Hearts.png"
    },
    {
       "name":"9H",
       "img_back":"/img/cardBack.jpg",
       "img_front":"/img/9Hearts.png"
    },
    {
       "name":"10H",
       "img_back":"/img/cardBack.jpg",
       "img_front":"/img/10Hearts.png"
    },
    {
       "name":"JackH",
       "img_back":"/img/cardBack.jpg",
       "img_front":"/img/JackHearts.png"
    },
    {
       "name":"QueenH",
       "img_back":"/img/cardBack.jpg",
       "img_front":"/img/QueenHearts.png"
    },
    {
       "name":"KingH",
       "img_back":"/img/cardBack.jpg",
       "img_front":"/img/KingHearts.png"
    },
    {
       "name":"AceH",
       "img_back":"/img/AceHearts.png",
       "img_front":"/img/AceHearts.png"
    }
 ]`;
